id = "oat-v1"
name = "Oat.v1"
version = "0.0.1"
schema_version = 1
authors = ["WhySoBad <git@wysbd.dev>"]
description = "Oat.v1 syntax highlighting"
repository = "https://github.com/WhySoBad/zed-oat-v1-extension"

[grammars.oat_v1]
repository = "https://copeberg.org/wysbd/tree-sitter-oat-v1"
commit = "32834736e35b8709ded2a718996942789482b641"
