id = "oat"
name = "Oat"
version = "0.0.1"
schema_version = 1
authors = ["WhySoBad <git@wysbd.dev>"]
description = "Oat language syntax highlighting"
repository = "https://github.com/WhySoBad/zed-oat-extension"

[grammars.oat]
repository = "https://github.com/WhySoBad/tree-sitter-oat"
commit = "220ff89be8f5d8f71fcb6b9e22115dd14cb2e083"
