id = "oat"
name = "Oat"
version = "0.0.4"
schema_version = 1
authors = ["WhySoBad <git@wysbd.dev>"]
description = "Oat language syntax highlighting"
repository = "https://github.com/WhySoBad/zed-oat-extension"

[grammars.oat]
repository = "https://github.com/WhySoBad/tree-sitter-oat"
commit = "e691fa14ea94df88fbf0701d26c67d1fa3d75dee"
