id = "oat"
name = "Oat"
version = "0.0.2"
schema_version = 1
authors = ["WhySoBad <git@wysbd.dev>"]
description = "Oat language syntax highlighting"
repository = "https://github.com/WhySoBad/zed-oat-extension"

[grammars.oat]
repository = "https://github.com/WhySoBad/tree-sitter-oat"
commit = "631480d9ae64f58eb801e59b3b314674867d6e61"
